### ISSUE TITLE
Initialize Documentation

### ISSUE THREAD

**Issue by crswong888** [idaholab/falcon#43]
The objective is to develop a website for the Falcon application using the MooseDocs Python module. We shall begin by setting up the basic configuration for the various Docs extensions, e.g., Content, Navigation (including the mega menu), Appsyntax, BibTex, SQA, etc., and later we can start to develop the homepage and the site map. A completed configuration will be such that developers can begin to add the general and body documentation using MooseDown (`.md`).

@rpodgorney @aeslaughter

**Comment by rpodgorney** [comment]
Thanks---let me know when you get the basics setup and I'll jump in

**Comment by crswong888** [comment]
@rpodgorney, please see my fork branch: [init-docs-43](https://github.com/crswong888/falcon/tree/init-docs-43) for a rough draft of the website config. I've generated pages for all FalconApp objects, and compiled a syntax list for them along with objects from the framework, tensor mechanics, and porous flow. Currently, the syntax list is the only thing linked in the mega menu. 

Assuming you've compiled physics modules and Falcon, you can run the server with the standard commands:

```
cd doc
./moosedocs.py build --serve
```

The next thing I need to know is what are the major components going to be, besides object syntax. For example, Installation, User Manual, Theory Manual, SQA, V&V, About, Contact, Help, etc. I also need to know how you want these pages to be organized for navigation, e.g., we could just do a top-level page "Installation", or we could nest it within some other headline like "Getting Started > Installation."

Anyways, that's how I suggest we proceed at this point. Otherwise, just let me know what you would like me to do next.

**Comment by rpodgorney** [comment]
I'll think on this and send suggestions tomorrow.  Thanks!

**Comment by rpodgorney** [comment]
Sorry for the questions…I haven’t worked in the doc system before.

I am getting this error, any ideas?


(moose) ***@***.***_64-apple-darwin13 doc % ./moosedocs.py build --serve

Traceback (most recent call last):

  File "./moosedocs.py", line 23, in <module>

    from MooseDocs import main

ModuleNotFoundError: No module named 'MooseDocs'



--
Robert K. Podgorney, PhD
Chief Computational Scientist
Advanced Scientific Computing Division
Idaho National Laboratory

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: ***@***.******@***.***>
Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.


From: crswong888 ***@***.***>
Reply-To: idaholab/falcon ***@***.***>
Date: Tuesday, May 25, 2021 at 5:31 PM
To: idaholab/falcon ***@***.***>
Cc: Robert Podgorney ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/falcon] Initialize Documentation (#43)


@rpodgorney<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frpodgorney&data=04%7C01%7Crobert.podgorney%40inl.gov%7C69c3314a492245e9380808d91fd5299c%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637575822650652938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p2dFbH6np8Y3fsaJYoVcKYzlySTQQwzIqYAbXJnzLY4%3D&reserved=0>, please see my fork branch: init-docs-43<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcrswong888%2Ffalcon%2Ftree%2Finit-docs-43&data=04%7C01%7Crobert.podgorney%40inl.gov%7C69c3314a492245e9380808d91fd5299c%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637575822650652938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FirLVhR0CEotIWHeL5wMwbhu4cGA1H8S%2F7ihs87MAlM%3D&reserved=0> for a rough draft of the website config. I've generated pages for all FalconApp objects, and compiled a syntax list for them along with objects from the framework, tensor mechanics, and porous flow. Currently, the syntax list is the only thing linked in the mega menu.

Assuming you've compiled physics modules and Falcon, you can run the server with the standard commands:

cd doc

./moosedocs.py build --serve

The next thing I need to know is what are the major components going to be, besides object syntax. For example, Installation, User Manual, Theory Manual, SQA, V&V, About, Contact, Help, etc. I also need to know how you want these pages to be organized for navigation, e.g., we could just do a top-level page "Installation", or we could nest it within some other headline like "Getting Started > Installation."

Anyways, that's how I suggest we proceed at this point. Otherwise, just let me know what you would like me to do next.

**Comment by crswong888** [comment]
@rpodgorney Ahh yes, I forgot I had the `MOOSE_DIR` environment variable set to `~/projects/moose/` in my bash profile, so I failed to notice this bug. The problem was I wasn't setting the right path to the submodule at `falcon/moose/`.

Please pull in my latest commit and try again.

**Comment by rpodgorney** [comment]
Thanks, have it up now.

Can you set it up similiat to Mastodon?  https://mooseframework.inl.gov/mastodon/

Top menu I need 1) getting started and 2) documentation

One the page itself just clone mastodon and then I can come in and edit….


--
Robert K. Podgorney, PhD
Chief Computational Scientist
Advanced Scientific Computing Division
Idaho National Laboratory

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: ***@***.******@***.***>
Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.


From: crswong888 ***@***.***>
Reply-To: idaholab/falcon ***@***.***>
Date: Wednesday, May 26, 2021 at 2:44 PM
To: idaholab/falcon ***@***.***>
Cc: Robert Podgorney ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/falcon] Initialize Documentation (#43)


@rpodgorney<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frpodgorney&data=04%7C01%7Crobert.podgorney%40inl.gov%7Cc388bb4076ab44d2ef6908d920871b19%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637576586917203650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Abn2c%2Ba9CVqCGLdlTE5L1yM2YLyG7%2Bej%2FfiGl%2F2b9%2BY%3D&reserved=0> Ahh yes, I forgot I had the MOOSE_DIR environment variable set to ~/projects/moose/ in my bash profile, so I failed to notice this bug. The problem was I wasn't setting the right path to the submodule at falcon/moose/.

Please pull in my latest commit and try again.
