### ISSUE TITLE
wrong time derivative in the mass balance

### ISSUE THREAD

**Issue by mrodb** [idaholab/falcon#8]
The time derivative term in the mass balance misses the derivatives respect to temperature.

**Comment by permcody** [comment]
I'm don't think that very many people are watching this repository right now. Is this reported issue something you plan to work on or are you requesting assistance?

**Comment by yidongxiainl** [comment]
Yes. That MIT student Mariana reported this issue. I asked her to
practicing creating a new issue, so that we can try to made progress
through this formal way.


Yidong Xia, PhD
Energy, Environment Science & Technology Directorate
Idaho National Laboratory
1955 N. Fremont Ave., PO Box 3560
Idaho Falls, ID 83415-2025
Tel: (208) 526-7490

**Comment by mrodb** [comment]
Hi all,
I created a ticket reporting this issue yesterday as Yidong suggested to me when I informed him about this issue.
Thank you
Mariana

**Comment by yidongxiainl** [comment]
For documentation purpose, let me declare here. The goal in this issue is to implement the finite different method for calculating the time derivatives in mass balance equation and energy conservation equations. We have doubt if this option could help reproduce test results of a problem ran by legacy Falcon code.

**Comment by mrodb** [comment]
Hello,
I modified the source code to correctly compute the time derivative term.
I used the correct analytical expression of the time derivative, which includes terms of partial derivatives respect to pressure and temperature.
The code compiles and converges, but results differ from results obtained with the old source FALCON version 2011.

**Comment by yidongxiainl** [comment]
Yes, I understand. That's why we need to try the old way to calculate the time derivatives in the current FALCON. We must narrow down our guess to see what is the cause of your discrepancy in the results.

**Comment by yidongxiainl** [comment]
Mariana, one more thing: there is no off-diagonal Jacobian terms of mass balance time derivative implemented in old FALCON 2011. You have done a correct way by including this part. But do you have any assurance that the old reference pressure results are "correct"?

**Comment by yidongxiainl** [comment]
@mrodb Hi Mariana, I've created a branch "xiay/issue8" for this issue. In this branch, I've added a finite difference approach way to compute mass time derivative. You are encouraged to get this branch and try to use "PTMassTimeDerivative_FD" instead of "PTMassTimeDerivative" in your problem. If you are not familiar with using Git to obtain this branch, let me know, and I will guide you through.

**Comment by friedmud** [comment]
Why would @mrodb 's code be wrong?  Why in the heck would you want to compare to an ad-hoc finite-difference?

Of course it's going to give slightly different values... it added some new terms.

**Comment by yidongxiainl** [comment]
Hi All,

This is no longer an issue. Mariana and I carried out both complete
analytical form of time derivative kernels and Jacobians and compared with
finite-difference approach for calculating Jacobians. The results match
well.


Yidong Xia, PhD
Energy, Environment Science & Technology Directorate
Idaho National Laboratory
1955 N. Fremont Ave., PO Box 3560
Idaho Falls, ID 83415-2025
Tel: (208) 526-7490

**Comment by rpodgorney** [comment]
Have you updated the code in regard to this issue?  If so, please comment and close.  Thanks

**Comment by rpodgorney** [comment]
cleaning up old issues
